server:
  port: 8085
spring:
  application:
    name: video-service
  data:
    mongodb:
      uri: mongodb+srv://devgroupentreprise_db_user:LWC5S7GRgfB2KN84@cluster-dga-1.xylzvke.mongodb.net/mbolo_video?retryWrites=true&w=majority
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

minio:
  endpoint: http://minio:9000
  access-key: ${MINIO_ACCESS_KEY:mbolo_admin}
  secret-key: ${MINIO_SECRET_KEY:mbolo_secret_2025}
  bucket: mbolo-videos
