server:
  port: 8082
spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb://localhost:27018/mbolo_user

minio:
  endpoint: http://minio:9000
  access-key: mbolo_admin
  secret-key: mbolo_secret_2025
  bucket: mbolo-avatars
