server:
  port: 8086
spring:
  application:
    name: moderation-service
  data:
    mongodb:
      uri: mongodb+srv://devgroupentreprise_db_user:LWC5S7GRgfB2KN84@cluster-dga-1.xylzvke.mongodb.net/mbolo_moderation?retryWrites=true&w=majority
