export const COLLECTIONS = {
  authUsers: "users_auth",
  refreshTokens: "refresh_tokens",
  passwordResetTokens: "password_reset_tokens",
  emailVerificationCodes: "email_verification_codes",
  userProfiles: "users_profile",
  userFollows: "user_follows",
  userFollowRequests: "user_follow_requests",
  posts: "posts",
  savedPosts: "saved_posts",
  comments: "comments",
  stories: "stories",
  notifications: "notifications",
  videos: "videos",
  groups: "groups",
  groupMembers: "group_members",
  pages: "pages",
  pageFollowers: "page_followers",
  conversations: "conversations",
  messages: "messages",
  reports: "reports",
  auditLogs: "audit_logs",
  platformSettings: "platform_settings",
};
